name = "AttractorNetworksRegularizers"
uuid = "54d82c36-3235-11e9-099b-91028afbf996"
authors = ["dylanfesta <darksnail@gmail.com>"]
version = "0.1.0"

[deps]
Calculus = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
